### ISSUE TITLE
Multiple Database Support?

### ISSUE THREAD

**Issue by joegaudet** [ezcater/activerecord-postgres_pub_sub#22]
Looking to add triggers to multiple db, any guidance there?

**Comment by tjwp** [comment]
I have not yet worked with multiple databases in Rails.

To try this, I would do the following: 

1. Run the generator from this gem with a `--database` argument as described here: https://guides.rubyonrails.org/active_record_multiple_databases.html#generators-and-migrations. If the migration is not generated in the correct directory for the database then move it there.
2. For the model that is triggering notifications, make sure that it inherits from an abstract record class that specifies the connection you want to use.
3. Finally when you are running the listener in application code wrap it within a block that specifies the connection to use:
```ruby
ActiveRecord::Base.connected_to(...) do
  ActiveRecord::PostgresPubSub::Listener.listen(...) { }
end
```

Within the `Listener`, `ActiveRecord::Base` is used to get a connection (https://github.com/ezcater/activerecord-postgres_pub_sub/blob/master/lib/activerecord/postgres_pub_sub/listener.rb#L57) so I'm guessing at how to switch it.

There are likely things that the gem could make easier in supporting multiple databases, such as accepting which database to use as an arg in the listen call, but if you get a chance to try this out please report back!
