### ISSUE TITLE
Please add/ensure compatibility with Rails 7.2

### ISSUE THREAD

**Issue by marco-carini** [ezcater/activerecord-postgres_pub_sub#34]
Currently, Rails is pinned to [Rails < 7.2](https://github.com/ezcater/activerecord-postgres_pub_sub/blob/main/activerecord-postgres_pub_sub.gemspec#L39); now that Rails 7.2 has been released, could this gem please be updated to maintain compatibility with the latest version of Rails. Thank you!

**Comment by marco-carini** [comment]
cc: @jmpage if you get a chance!

**Comment by jmpage** [comment]
@marco-carini version 3.1.0 of this gem with dependency constraints altered to allow it to be installed alongside activerecord 7.2 has been pushed to rubygems.
